server:
  port: 8082
logging:
  level:
    root: info
elasticsearch:
  # set in IDE under dev environment
  hostAndPort: ${ELASTIC_SEARCH_HOST_AND_PORT}
#spring:
#  elasticsearch:
#    uris: http://localhost:9200
#    username: elastic
#    password: mfvBqJ6ZuqxOsw_FCj=w