server:
  port: 8082
elasticsearch:
  # set in IDE under dev environment
  hostAndPort: ${ELASTIC_SEARCH_HOST_AND_PORT}
#spring:
#  elasticsearch:
#    uris: http://localhost:9200
#    username: elastic
#    password: mfvBqJ6ZuqxOsw_FCj=w
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/digger?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQLDialect
